### ISSUE TITLE
Alpine Expression Error: codeEditorFormComponent is not defined

### ISSUE THREAD

**Issue by solutionforestteam** [SebastiaanKloos/filament-code-editor#1]
Alpine Expression Error: codeEditorFormComponent is not defined

Expression: "codeEditorFormComponent({
            state: $wire.entangle('custom_css').defer,
        })"

 <div x-data=​"codeEditorFormComponent({
            state:​ $wire.entangle('custom_css')​.defer,
        }​)​">​…​</div>​
handleError @ module.esm.js:420
eval @ module.esm.js:486
Promise.catch (async)
eval @ module.esm.js:486
tryCatch @ module.esm.js:413
evaluate @ module.esm.js:431
eval @ module.esm.js:2611
eval @ module.esm.js:1142
flushHandlers @ module.esm.js:543
stopDeferring @ module.esm.js:548
deferHandlingDirectives @ module.esm.js:551
initTree @ module.esm.js:754
eval @ module.esm.js:714
start @ module.esm.js:713
eval @ app.js:11
./resources/js/app.js @ app.js?id=83a004fdc7cbe50d88d536f107e4e69a:40
__webpack_require__ @ app.js?id=83a004fdc7cbe50d88d536f107e4e69a:107
(anonymous) @ app.js?id=83a004fdc7cbe50d88d536f107e4e69a:253
__webpack_require__.O @ app.js?id=83a004fdc7cbe50d88d536f107e4e69a:146
(anonymous) @ app.js?id=83a004fdc7cbe50d88d536f107e4e69a:255
(anonymous) @ app.js?id=83a004fdc7cbe50d88d536f107e4e69a:257

**Comment by SebastiaanKloos** [comment]
@solutionforestteam where are you using the code editor field? Could it be that you are using it in a form without Filament Admin? Than you should add the js file on your site manually. I'll add that to the docs.

**Comment by SebastiaanKloos** [comment]
@solutionforestteam I've added documentation for using this package without Filament Admin. See:
https://github.com/SebastiaanKloos/filament-code-editor#usage
